/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkyeliteRouteImport } from './routes/skyelite'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as HaloRouteImport } from './routes/halo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkyeliteIndexRouteImport } from './routes/skyelite.index'
import { Route as WorkIosRouteImport } from './routes/work.ios'
import { Route as WorkAuraiRouteImport } from './routes/work.aurai'
import { Route as WorkAeonRouteImport } from './routes/work.aeon'
import { Route as SkyeliteStoryRouteImport } from './routes/skyelite.story'
import { Route as SkyeliteRatesRouteImport } from './routes/skyelite.rates'
import { Route as SkyeliteFaqRouteImport } from './routes/skyelite.faq'
import { Route as SkyeliteBookRouteImport } from './routes/skyelite.book'
import { Route as SkyeliteBenefitsRouteImport } from './routes/skyelite.benefits'

const SkyeliteRoute = SkyeliteRouteImport.update({
  id: '/skyelite',
  path: '/skyelite',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const HaloRoute = HaloRouteImport.update({
  id: '/halo',
  path: '/halo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyeliteIndexRoute = SkyeliteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkyeliteRoute,
} as any)
const WorkIosRoute = WorkIosRouteImport.update({
  id: '/work/ios',
  path: '/work/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAuraiRoute = WorkAuraiRouteImport.update({
  id: '/work/aurai',
  path: '/work/aurai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAeonRoute = WorkAeonRouteImport.update({
  id: '/work/aeon',
  path: '/work/aeon',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyeliteStoryRoute = SkyeliteStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteRatesRoute = SkyeliteRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteFaqRoute = SkyeliteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteBookRoute = SkyeliteBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SkyeliteRoute,
} as any)
const SkyeliteBenefitsRoute = SkyeliteBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => SkyeliteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/halo': typeof HaloRoute
  '/portfolio': typeof PortfolioRoute
  '/skyelite': typeof SkyeliteRouteWithChildren
  '/skyelite/benefits': typeof SkyeliteBenefitsRoute
  '/skyelite/book': typeof SkyeliteBookRoute
  '/skyelite/faq': typeof SkyeliteFaqRoute
  '/skyelite/rates': typeof SkyeliteRatesRoute
  '/skyelite/story': typeof SkyeliteStoryRoute
  '/work/aeon': typeof WorkAeonRoute
  '/work/aurai': typeof WorkAuraiRoute
  '/work/ios': typeof WorkIosRoute
  '/skyelite/': typeof SkyeliteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/halo': typeof HaloRoute
  '/portfolio': typeof PortfolioRoute
  '/skyelite/benefits': typeof SkyeliteBenefitsRoute
  '/skyelite/book': typeof SkyeliteBookRoute
  '/skyelite/faq': typeof SkyeliteFaqRoute
  '/skyelite/rates': typeof SkyeliteRatesRoute
  '/skyelite/story': typeof SkyeliteStoryRoute
  '/work/aeon': typeof WorkAeonRoute
  '/work/aurai': typeof WorkAuraiRoute
  '/work/ios': typeof WorkIosRoute
  '/skyelite': typeof SkyeliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/halo': typeof HaloRoute
  '/portfolio': typeof PortfolioRoute
  '/skyelite': typeof SkyeliteRouteWithChildren
  '/skyelite/benefits': typeof SkyeliteBenefitsRoute
  '/skyelite/book': typeof SkyeliteBookRoute
  '/skyelite/faq': typeof SkyeliteFaqRoute
  '/skyelite/rates': typeof SkyeliteRatesRoute
  '/skyelite/story': typeof SkyeliteStoryRoute
  '/work/aeon': typeof WorkAeonRoute
  '/work/aurai': typeof WorkAuraiRoute
  '/work/ios': typeof WorkIosRoute
  '/skyelite/': typeof SkyeliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/halo'
    | '/portfolio'
    | '/skyelite'
    | '/skyelite/benefits'
    | '/skyelite/book'
    | '/skyelite/faq'
    | '/skyelite/rates'
    | '/skyelite/story'
    | '/work/aeon'
    | '/work/aurai'
    | '/work/ios'
    | '/skyelite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/halo'
    | '/portfolio'
    | '/skyelite/benefits'
    | '/skyelite/book'
    | '/skyelite/faq'
    | '/skyelite/rates'
    | '/skyelite/story'
    | '/work/aeon'
    | '/work/aurai'
    | '/work/ios'
    | '/skyelite'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/halo'
    | '/portfolio'
    | '/skyelite'
    | '/skyelite/benefits'
    | '/skyelite/book'
    | '/skyelite/faq'
    | '/skyelite/rates'
    | '/skyelite/story'
    | '/work/aeon'
    | '/work/aurai'
    | '/work/ios'
    | '/skyelite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HaloRoute: typeof HaloRoute
  PortfolioRoute: typeof PortfolioRoute
  SkyeliteRoute: typeof SkyeliteRouteWithChildren
  WorkAeonRoute: typeof WorkAeonRoute
  WorkAuraiRoute: typeof WorkAuraiRoute
  WorkIosRoute: typeof WorkIosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skyelite': {
      id: '/skyelite'
      path: '/skyelite'
      fullPath: '/skyelite'
      preLoaderRoute: typeof SkyeliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halo': {
      id: '/halo'
      path: '/halo'
      fullPath: '/halo'
      preLoaderRoute: typeof HaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skyelite/': {
      id: '/skyelite/'
      path: '/'
      fullPath: '/skyelite/'
      preLoaderRoute: typeof SkyeliteIndexRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/work/ios': {
      id: '/work/ios'
      path: '/work/ios'
      fullPath: '/work/ios'
      preLoaderRoute: typeof WorkIosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/aurai': {
      id: '/work/aurai'
      path: '/work/aurai'
      fullPath: '/work/aurai'
      preLoaderRoute: typeof WorkAuraiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/aeon': {
      id: '/work/aeon'
      path: '/work/aeon'
      fullPath: '/work/aeon'
      preLoaderRoute: typeof WorkAeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skyelite/story': {
      id: '/skyelite/story'
      path: '/story'
      fullPath: '/skyelite/story'
      preLoaderRoute: typeof SkyeliteStoryRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/rates': {
      id: '/skyelite/rates'
      path: '/rates'
      fullPath: '/skyelite/rates'
      preLoaderRoute: typeof SkyeliteRatesRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/faq': {
      id: '/skyelite/faq'
      path: '/faq'
      fullPath: '/skyelite/faq'
      preLoaderRoute: typeof SkyeliteFaqRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/book': {
      id: '/skyelite/book'
      path: '/book'
      fullPath: '/skyelite/book'
      preLoaderRoute: typeof SkyeliteBookRouteImport
      parentRoute: typeof SkyeliteRoute
    }
    '/skyelite/benefits': {
      id: '/skyelite/benefits'
      path: '/benefits'
      fullPath: '/skyelite/benefits'
      preLoaderRoute: typeof SkyeliteBenefitsRouteImport
      parentRoute: typeof SkyeliteRoute
    }
  }
}

interface SkyeliteRouteChildren {
  SkyeliteBenefitsRoute: typeof SkyeliteBenefitsRoute
  SkyeliteBookRoute: typeof SkyeliteBookRoute
  SkyeliteFaqRoute: typeof SkyeliteFaqRoute
  SkyeliteRatesRoute: typeof SkyeliteRatesRoute
  SkyeliteStoryRoute: typeof SkyeliteStoryRoute
  SkyeliteIndexRoute: typeof SkyeliteIndexRoute
}

const SkyeliteRouteChildren: SkyeliteRouteChildren = {
  SkyeliteBenefitsRoute: SkyeliteBenefitsRoute,
  SkyeliteBookRoute: SkyeliteBookRoute,
  SkyeliteFaqRoute: SkyeliteFaqRoute,
  SkyeliteRatesRoute: SkyeliteRatesRoute,
  SkyeliteStoryRoute: SkyeliteStoryRoute,
  SkyeliteIndexRoute: SkyeliteIndexRoute,
}

const SkyeliteRouteWithChildren = SkyeliteRoute._addFileChildren(
  SkyeliteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HaloRoute: HaloRoute,
  PortfolioRoute: PortfolioRoute,
  SkyeliteRoute: SkyeliteRouteWithChildren,
  WorkAeonRoute: WorkAeonRoute,
  WorkAuraiRoute: WorkAuraiRoute,
  WorkIosRoute: WorkIosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
